// AUTO-GENERATED from Mongoose model "Unit" — do not edit by hand
// Run: npm run generate:mcp-schemas -- --models Unit
import { z } from "zod";
import { dateSchema, objectIdSchema } from "@/mcptools/shared";

const inputModeSchema = z.enum(["FILE", "CONTENT"]);
const optionUserSchema = z.enum(["REGISTRY", "ALL", "CUSTOM", "COURSE_USER_GROUP"]);
const sourceOrginSchema = z.enum(["ELMSS"]);
const typeSchema = z.enum(["CONTENT", "WEBPAGE", "VIDEO", "AUDIO", "DOCUMENT", "SCORM", "IFRAME", "TEST", "SURVEY", "ASSIGNMENT", "LIVESTREAMING", "CLASSROOM", "MSTEAMS_MEETING", "HYBRID", "LINK", "SECTION", "SUB_SECTION", "FILES", "LTI"]);

export const unitSchema = z.object({
  _id: objectIdSchema.optional(),
  activationDate: z.object({
    active: dateSchema.optional(),
    deactive: dateSchema.optional(),
  }).optional(),
  adaptiveSetup: z.object({
    _id: objectIdSchema.optional(),
    attemptRules: z.array(z.object({
      _id: objectIdSchema.optional(),
      attemptCount: z.number().optional(),
      passScore: z.number().optional(),
      skipLesson: z.array(objectIdSchema).optional(),
    })).optional(),
    course: objectIdSchema.optional(),
    createdBy: objectIdSchema.optional(),
    extractedContent: z.string().optional(),
    input: z.object({
      attempt: z.string().optional(),
      content: z.string().optional(),
      files: z.array(objectIdSchema).optional(),
      inputMode: inputModeSchema.optional(),
      mode: z.string().optional(),
      passScore: z.number().optional(),
      questionCount: z.number().optional(),
      questions: z.array(z.object({
        count: z.number(),
        manualMarking: z.boolean(),
        type: z.string(),
      })).optional(),
      title: z.string().optional(),
    }).optional(),
    isAdaptive: z.boolean().optional(),
    supplementaryLesson: z.array(objectIdSchema).optional(),
    updatedBy: objectIdSchema.optional(),
  }).optional(),
  allowWebCrawl: z.boolean().optional(),
  clone: objectIdSchema.optional(),
  combinedCourses: z.array(objectIdSchema).optional(),
  combinedUnit: objectIdSchema.optional(),
  combinedUnits: z.array(objectIdSchema).optional(),
  complete: z.unknown().optional(),
  completedBy: z.string().optional(),
  config: z.unknown().optional(),
  content: z.string().optional(),
  contentReviewComments: z.string().optional(),
  contentReviewStatus: z.string().optional(),
  contentReviewUpdate: dateSchema.optional(),
  course: objectIdSchema.optional(),
  courseCentre: z.array(objectIdSchema).optional(),
  courseUnit: objectIdSchema.optional(),
  createdAt: dateSchema.optional(),
  externalFiles: z.array(z.unknown()).optional(),
  file: objectIdSchema.optional(),
  group: objectIdSchema.optional(),
  importLesson: z.boolean().optional(),
  isCombinedClass: z.boolean().optional(),
  isCombinedClassParent: z.boolean().optional(),
  isMinutes: z.boolean().optional(),
  isSelfLearning: z.boolean().optional(),
  isSupplementary: z.boolean().optional(),
  learningHours: z.number().optional(),
  link: z.string().optional(),
  locationMaster: objectIdSchema.optional(),
  ltiPackages: z.array(z.object({
    _id: objectIdSchema.optional(),
    packageId: z.string().optional(),
    title: z.string().optional(),
    url: z.string().optional(),
  })).optional(),
  maxAudioSize: z.number().optional(),
  maxFileSize: z.number().optional(),
  maxTextCharactor: z.number().optional(),
  maxVideoSize: z.number().optional(),
  modeOfTraining: z.string().optional(),
  noOfAudioFile: z.number().optional(),
  noOfFiles: z.number().optional(),
  noOfVideoFile: z.number().optional(),
  oldStatus: z.string().optional(),
  omitUsers: z.array(objectIdSchema).optional(),
  optionUser: optionUserSchema.optional(),
  order: z.number(),
  referenceAnswer: z.string().optional(),
  restrictAccess: z.boolean().optional(),
  rubric: objectIdSchema.optional(),
  section: objectIdSchema.optional(),
  sourceOrgin: sourceOrginSchema.optional(),
  status: z.string(),
  submissions: z.string(),
  submissionsType: z.string(),
  subSection: objectIdSchema.optional(),
  tableStructure: z.boolean().optional(),
  time: z.object({
    begin: dateSchema.optional(),
    due: dateSchema.optional(),
    end: dateSchema.optional(),
  }).optional(),
  timezone: z.string().optional(),
  title: z.string(),
  titleExtenstion: z.string().optional(),
  type: typeSchema,
  typeData: z.string().optional(),
  updatedAt: dateSchema.optional(),
  user: objectIdSchema.optional(),
  userGroups: z.array(objectIdSchema).optional(),
  users: z.array(objectIdSchema).optional(),
  __v: z.number().optional(),
});

export type Unit = z.infer<typeof unitSchema>;
