// AUTO-GENERATED from Mongoose model "UserUnit" — do not edit by hand
// Run: npm run generate:mcp-schemas -- --models UserUnit
import { z } from "zod";
import { dateSchema, objectIdSchema } from "@/mcptools/shared";

export const userUnitSchema = z.object({
  _id: objectIdSchema.optional(),
  adaptiveAttempt: z.number().optional(),
  adaptiveSetup: z.unknown().optional(),
  aiReply: z.object({
    evaluatedAt: dateSchema.optional(),
    feedback: z.string().optional(),
    modelUsed: z.string().optional(),
    plagiarismCheck: z.object({
      aiRewritingDetected: z.boolean().optional(),
      highlightedText: z.string().optional(),
      matches: z.array(z.object({
        _id: objectIdSchema.optional(),
        reason: z.string().optional(),
        reference: z.string().optional(),
        section: z.string().optional(),
        similarity: z.number().optional(),
        source: z.string().optional(),
      })).optional(),
      paraphrasingDetected: z.boolean().optional(),
      percentage: z.number().optional(),
      score: z.number().optional(),
      summary: z.string().optional(),
    }).optional(),
    rubricBreakdown: z.array(z.object({
      _id: objectIdSchema.optional(),
      aiScore: z.number().optional(),
      instructorScore: z.number().optional(),
      name: z.string().optional(),
      reason: z.string().optional(),
      score: z.number().optional(),
      suggestion: z.string().optional(),
    })).optional(),
    total: z.number().optional(),
  }).optional(),
  bookMark: z.unknown().optional(),
  complete: z.unknown().optional(),
  completedBy: z.string().optional(),
  config: z.unknown().optional(),
  content: z.string().optional(),
  course: objectIdSchema.optional(),
  createAiAssignment: z.boolean().optional(),
  createdAt: dateSchema.optional(),
  duration: z.number().optional(),
  file: objectIdSchema.optional(),
  isCompleted: z.boolean().optional(),
  isDurationEnd: z.boolean().optional(),
  link: z.string().optional(),
  microLearningContent: z.string().optional(),
  OldPoints: z.number().optional(),
  oldStatus: z.string().optional(),
  penalty: z.string().optional(),
  points: z.number().optional(),
  reAttempt: z.boolean().optional(),
  result: z.unknown().optional(),
  shuffleOrder: z.array(z.unknown()).optional(),
  status: z.string(),
  statusUpdateBy: z.string().optional(),
  submittedDate: dateSchema.optional(),
  testScreenShot: z.array(z.unknown()).optional(),
  testStartTime: z.string().optional(),
  title: z.string().optional(),
  totalPoints: z.number().optional(),
  type: z.string().optional(),
  typeData: z.string().optional(),
  unit: objectIdSchema.optional(),
  unitStatus: z.string(),
  updatedAt: dateSchema.optional(),
  user: objectIdSchema.optional(),
  userFile: objectIdSchema.optional(),
  userQuestions: z.array(z.unknown()).optional(),
  userSubmitted: z.array(z.object({
    _id: objectIdSchema.optional(),
    endDate: z.string().optional(),
    startDate: z.string().optional(),
  })).optional(),
  whileCreate: z.boolean().optional(),
  __v: z.number().optional(),
});

export type UserUnit = z.infer<typeof userUnitSchema>;
